HOSTNAME = '127.0.0.1'
PORT = '3306'
DATABASE = '****'
USERNAME = 'root'
PASSWORD = '****'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME, PASSWORD, HOSTNAME, PORT, DATABASE)
SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True
SECRET_KEY = 'exercise_log_dy'

MAIL_SERVER = 'smtp.qq.com'
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_DEBUG = True
MAIL_USERNAME = '****@**.**'
MAIL_PASSWORD = '******'
MAIL_DEFAULT_SENDER = '****@**.**'
# MAIL_MAX_EMAILS = ''
# MAIL_SUPPRESS_SEND = ''
# MAIL_ASCII_ATTACHMENTS = ''
